### ISSUE TITLE
Missing native dependency for emulator

### ISSUE THREAD

**Issue by gyulavoros** [idnow/de.idnow.android.sdk#13]
Running the SDK (`3.19.0`) on a HAXM enabled emulator (x86_64) throws the following exception:

```
2020-03-11 18:03:53.993 17007-17007/{package} E/AndroidRuntime: FATAL EXCEPTION: main
    Process: {package}, PID: 17007
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/{package}-F56_WvVsmGFbgsiEQiBgWw==/base.apk"],nativeLibraryDirectories=[/data/app/{package}-F56_WvVsmGFbgsiEQiBgWw==/lib/x86, /data/app/{package}-F56_WvVsmGFbgsiEQiBgWw==/base.apk!/lib/x86, /system/lib, /system/product/lib]]] couldn't find "libidnow_tracking.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at de.idnow.core.IDnowSDK.<init>(:1)
        at de.idnow.core.IDnowSDK.getInstance(Unknown Source:21)
        ...
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

```

By extracting the AAR package it seems `libidnow_tracking.so` really is missing. Is this expected? If yes, it would be nice to update the `README.md` file, that emulator is not supported.

<img width="652" alt="Screenshot 2020-03-11 at 18 05 21" src="https://user-images.githubusercontent.com/932504/76444207-e16cd500-63c3-11ea-959c-5607a18f8d12.png">

**Comment by rfejer-idnow** [comment]
Emulators are supported in general, but not the ones based on the x86 architecture. In July 2019 we dropped support for x86, as the very small number of x86-only devices couldn't justify the increase of our AAR library size, nor the maintenance of two libraries (for ARM and x86).

In our changelog for version 3.9.0 we mentioned "removed support for the x86 architecture", but I agree this is not that visible as in the readme file. Will update README.md too, thanks!
