### ISSUE TITLE
BankIdent screen is crashing on my app

### ISSUE THREAD

**Issue by bastienpaulfr** [idnow/de.idnow.android.sdk#74]
Version : 4.19.1

## Description

Auto ident screen is crashing when I arrive to BankIdent step. 

## Logcat

```
    --------- beginning of crash
2022-09-06 18:21:59.637 3132-3132/xxx.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: xxx.debug, PID: 3132
    java.lang.NoClassDefFoundError: Failed resolution of: Lcoil/compose/ImagePainter$ExecuteCallback;
        at com.fintecsystems.xs2awizard.form.components.LogoLineKt.LogoLine(LogoLine.kt:143)
        at com.fintecsystems.xs2awizard.XS2AWizardKt.FormLines(XS2AWizard.kt:123)
        at com.fintecsystems.xs2awizard.XS2AWizardKt.FormLinesContainer(XS2AWizard.kt:151)
        at com.fintecsystems.xs2awizard.XS2AWizardKt$XS2AWizard$2.invoke(XS2AWizard.kt:71)
        at com.fintecsystems.xs2awizard.XS2AWizardKt$XS2AWizard$2.invoke(XS2AWizard.kt:58)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:145)
        at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2351)
        at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2618)
        at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3205)
        at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3183)
        at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:252)
        at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
        at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3183)
        at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3148)
        at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:746)
        at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:876)
        at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:107)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:485)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:454)
        at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1008)
        at android.view.Choreographer.doCallbacks(Choreographer.java:809)
        at android.view.Choreographer.doFrame(Choreographer.java:740)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8512)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@fbea450, androidx.compose.ui.platform.MotionDurationScaleImpl@1c8649, StandaloneCoroutine{Cancelling}@2859b4e, AndroidUiDispatcher@489146f]
    Caused by: java.lang.ClassNotFoundException: Didn't find class "coil.compose.ImagePainter$ExecuteCallback" on path: DexPathList[[dex file "/data/data/xxx.debug/code_cache/.overlay/base.apk/classes5.dex", zip file "/data/app/~~JQkDr7RB1oRMqwmEFTlZuQ==/xxx.debug-uEq7Ggcwu-lB82XZxiTAHw==/base.apk"],nativeLibraryDirectories=[/data/app/~~JQkDr7RB1oRMqwmEFTlZuQ==/xxx.debug-uEq7Ggcwu-lB82XZxiTAHw==/lib/arm64, /data/app/~~JQkDr7RB1oRMqwmEFTlZuQ==/xxx.debug-uEq7Ggcwu-lB82XZxiTAHw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]
2022-09-06 18:21:59.637 3132-3132/xxx.debug E/AndroidRuntime:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 36 more
```

## Video

https://user-images.githubusercontent.com/87853987/188688211-350e3ea3-20f5-4a08-bdc1-b4cc2e0ba5e7.mp4

## Additional info

I am using AutoIdent SDK in my app. It is working well in IDNow app and a simple demo app.

**Comment by sebastian-schipor-idnow** [comment]
@bastienpaulfr there are some things you can check. Since the IDnow app is working well, please make sure that inside your app:
- you do not alter the sdk's proguard rules 
- you do not alter the 3rd party dependencies of our sdk (do not exclude any of them)
- do you have an additional coil/compose library in your app? If yes, what version?
- try to clean/sync gradle with project file

If any of these do not work, please provide us more info on your app setup: gradle version, build type, send us a sample of you build.gradle file of app level.

**Comment by bastienpaulfr** [comment]
Hello @sebastian-schipor-idnow 

I've run `./gradlew app:androidDependencies` and I get this for coil:

```
+--- io.coil-kt:coil-compose:2.0.0@aar
+--- io.coil-kt:coil-compose-base:2.0.0@aar
```

Which version is used by AutoIdent and VideoIdent since both SDK are embedded into the same app ?

**Comment by bastienpaulfr** [comment]
Hello @sebastian-schipor-idnow 

Actually, this is the root cause of the issue. Our app is somehow using `io.coil-kt:coil-compose:2.0.0@aar` whereas they are some dependencies that can work only with `coil` at version `1.4.0`. 

I'm thinking about Tink -> https://github.com/FinTecSystems/xs2a-android

Do you have some ideas how we can proceed ?

**Comment by sebastian-schipor-idnow** [comment]
@bastienpaulfr we are using Fintech Systems's library in our sdk (`v4.3.1`) which is using the coild `v1.4.0`
We will update the fintech systems's SDK to one of the latest versions which will contain the latest version of coil library. We will keep you posted when this will come out!

In the meantime, you can:
- try to force the coil v1.4.0 version from the library you have included in your app (the one who has v1.4.0 coil version)
```
configurations.all { 
    resolutionStrategy.force 'io.coil-kt:coil-compose:1.4.0'
}
```

OR

- exclude the coil v2.0.0 from the library which includes it
```
implementation ('your_library_which_includes_coil'){
        exclude group: 'io.coil-kt', module:'coil-compose'
    }
```

**Comment by bastienpaulfr** [comment]
Hi @sebastian-schipor-idnow 

Thanks for your suggestions, I'll try them this morning. 

Could you still give us an ETA for the Fintech Systems's library update ?

Many thanks,

**Comment by bastienpaulfr** [comment]
Hi @sebastian-schipor-idnow 

When I force coil dependency to 1.4.0, I'm getting this crash

```

2022-09-08 10:12:12.673 9068-9068/xxx.debug E/ContextImpl: Tried to access visual service WindowManager from a non-visual Context:com.qonto.qonto.DebugQontoApp@e3adb94 Visual services, such as WindowManager, WallpaperService or LayoutInflater should be accessed from Activity or other visual Context. Use an Activity or a Context created with Context#createWindowContext(int, Bundle), which are adjusted to the configuration and visual bounds of an area on screen.
    java.lang.IllegalAccessException: Tried to access visual service WindowManager from a non-visual Context:com.qonto.qonto.DebugQontoApp@e3adb94
        at android.app.ContextImpl.getSystemService(ContextImpl.java:1996)
        at android.content.ContextWrapper.getSystemService(ContextWrapper.java:821)
        at de.idnow.insights.DeviceInfo.getResolution(DeviceInfo.java:84)
        at de.idnow.insights.CrashDetails.getCrashData(CrashDetails.java:428)
        at de.idnow.insights.ConnectionQueue.sendCrashReport(ConnectionQueue.java:416)
        at de.idnow.insights.Insights$4.uncaughtException(Insights.java:1298)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
        at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:61)
        at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:33)
        at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:196)
        at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:229)
        at kotlinx.coroutines.JobSupport.continueCompleting(JobSupport.kt:935)
        at kotlinx.coroutines.JobSupport.access$continueCompleting(JobSupport.kt:27)
        at kotlinx.coroutines.JobSupport$ChildCompletion.invoke(JobSupport.kt:1155)
        at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1520)
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:323)
        at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:240)
        at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:906)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:863)
        at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:828)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8512)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
2022-09-08 10:12:12.685 9068-10675/xxx.debug I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2022-09-08 10:12:12.685 9068-10675/xxx.debug I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
2022-09-08 10:12:12.763 9068-9995/xxx.debug D/libcrashlytics: Initializing libcrashlytics version 3.2.0
2022-09-08 10:12:12.764 9068-9995/xxx.debug D/libcrashlytics: Initializing native crash handling successful.
2022-09-08 10:12:12.769 9068-9068/xxx.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: xxx.debug, PID: 9068
    java.lang.NoSuchFieldError: No field Companion of type Lcoil/ImageLoader$Companion; in class Lcoil/ImageLoader; or its superclasses (declaration of 'coil.ImageLoader' appears in /data/app/~~myMG6rcaF2HmDGFP9SYrLg==/xxx.debug-KUbpDnLonycgs2GUWO5lbg==/base.apk!classes30.dex)
        at coil.Coil.newImageLoader(Coil.kt:79)
        at coil.Coil.imageLoader(Coil.kt:24)
        at coil.compose.ImageLoaderProvidableCompositionLocal.getCurrent(LocalImageLoader.kt:64)
        at com.fintecsystems.xs2awizard.form.components.LogoLineKt.LogoLine(LogoLine.kt:145)
        at com.fintecsystems.xs2awizard.XS2AWizardKt.FormLines(XS2AWizard.kt:123)
        at com.fintecsystems.xs2awizard.XS2AWizardKt.FormLinesContainer(XS2AWizard.kt:151)
        at com.fintecsystems.xs2awizard.XS2AWizardKt$XS2AWizard$2.invoke(XS2AWizard.kt:71)
        at com.fintecsystems.xs2awizard.XS2AWizardKt$XS2AWizard$2.invoke(XS2AWizard.kt:58)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:145)
        at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2351)
        at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2618)
        at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3205)
        at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(Composer.kt:3183)
        at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:252)
        at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
        at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3183)
        at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:3148)
        at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:746)
        at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:876)
        at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:107)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:485)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:454)
        at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1008)
        at android.view.Choreographer.doCallbacks(Choreographer.java:809)
        at android.view.Choreographer.doFrame(Choreographer.java:740)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8512)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.PausableMonotonicFrameClock@ed69939, androidx.compose.ui.platform.MotionDurationScaleImpl@f24cb7e, StandaloneCoroutine{Cancelling}@a1f38df, AndroidUiDispatcher@e19592c]
```

Any ideas ?

**Comment by bastienpaulfr** [comment]
Hello @sebastian-schipor-idnow 

I've forced the version of `xs2awizard` lib to `3.5.4` that is the first version depending on coil 2.x.x

```
configurations.all {
    resolutionStrategy.force "com.fintecsystems:xs2awizard:3.5.4"
}
```

I've managed to perform the BankIdent process. Nevertheless I do not know if there are any side effect of doing that. Could you please check and keep me posted on that ?

**Comment by sebastian-schipor-idnow** [comment]
@bastienpaulfr we do not recommend to use this in production environment, as we do not know what other implication the new library might have. 
You can use it like this on your local environment for now, until we will make an official release. We do not have a timeline yet, but we will keep you posted once we know more.

**Comment by bastienpaulfr** [comment]
I'll check this asap and keep you posted.

**Comment by sebastian-schipor-idnow** [comment]
@bastienpaulfr I can see that v3.10.1 requires android minSDK update. Please check with `v3.9.1`

**Comment by bastienpaulfr** [comment]
This version makes BankIdent process crash

```

2022-09-08 14:25:51.083 11731-11731/eu.qonto.qonto.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: eu.qonto.qonto.debug, PID: 11731
    java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Ljava/lang/String;Lkotlin/jvm/functions/Function1;Lkotlin/jvm/functions/Function0;Lkotlin/jvm/functions/Function1;Lkotlin/jvm/functions/Function0;Lkotlin/jvm/functions/Function1;Lkotlin/jvm/functions/Function0;Lcom/fintecsystems/xs2awizard/components/theme/IXS2ATheme;)V in class Lcom/fintecsystems/xs2awizard/components/XS2AWizardConfig; or its super classes (declaration of 'com.fintecsystems.xs2awizard.components.XS2AWizardConfig' appears in /data/app/~~It_zsZu7MqOMJ_U4P_XrHA==/eu.qonto.qonto.debug-owNcK6gvAYWZ3eBANuYgZg==/base.apk!classes30.dex)
        at de.idnow.core.ui.main.f.onViewCreated(SourceFile:2126)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3128)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1890)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1808)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1751)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:538)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8512)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
```

**Comment by sebastian-schipor-idnow** [comment]
@bastienpaulfr thanks, it seems that this version requires some code changes.

**Comment by sebastian-schipor-idnow** [comment]
@bastienpaulfr we have released a new AI SDK version **5.0.0** which contains a new version of Fintec Systems SDK. Please try it out and let us know if the crash still persists.
