### ISSUE TITLE
Crash launching Video Selfie

### ISSUE THREAD

**Issue by bastienpaulfr** [idnow/de.idnow.android.sdk#76]
Hello,

I've got this crash in launching video selfie. This crash does not occur every time, but I've got it twice for 6 tries.

```

2022-09-08 11:57:29.830 18461-18461/eu.qonto.qonto.debug E/ContextImpl: Tried to access visual service WindowManager from a non-visual Context:com.qonto.qonto.DebugQontoApp@5bd7ff5 Visual services, such as WindowManager, WallpaperService or LayoutInflater should be accessed from Activity or other visual Context. Use an Activity or a Context created with Context#createWindowContext(int, Bundle), which are adjusted to the configuration and visual bounds of an area on screen.
    java.lang.IllegalAccessException: Tried to access visual service WindowManager from a non-visual Context:com.qonto.qonto.DebugQontoApp@5bd7ff5
        at android.app.ContextImpl.getSystemService(ContextImpl.java:1996)
        at android.content.ContextWrapper.getSystemService(ContextWrapper.java:821)
        at de.idnow.insights.DeviceInfo.getResolution(DeviceInfo.java:84)
        at de.idnow.insights.DeviceInfo.getMetrics(DeviceInfo.java:241)
        at de.idnow.insights.ConnectionQueue.beginSession(ConnectionQueue.java:171)
        at de.idnow.insights.ModuleSessions.beginSessionInternal(ModuleSessions.java:29)
        at de.idnow.insights.ModuleSessions$Sessions.beginSession(ModuleSessions.java:81)
        at de.idnow.core.util.k.a(SourceFile:5383)
        at de.idnow.core.ui.qes.IDnowQesNameConfirmingActivity.onCreate(SourceFile:43)
        at android.app.Activity.performCreate(Activity.java:8198)
        at android.app.Activity.performCreate(Activity.java:8182)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3765)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3968)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8512)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

I'm using the version 4.19.1

@sebastian-schipor-idnow

**Comment by sebastian-schipor-idnow** [comment]
@bastienpaulfr can you provide more info about how to reproduce this crash? It crashes immediately after you press start on the Video Selfie instructions screen?
Also, please provide the ident token you used to reproduce it.

**Comment by bastienpaulfr** [comment]
I'll try to reproduce it to provide you an Ident-ID. I normally display it in logs but when they are many of them it disapear quite quickly. 

It does not crash immediately after pressing the button but rather when the screen needs to change. I mean that because it takes 2 minutes between the button press and the screen change, this is the reason why it is not immediate.

**Comment by bastienpaulfr** [comment]
It might be related to this log as well : 

```

2022-09-08 14:20:33.441 9951-9951/eu.qonto.qonto.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: eu.qonto.qonto.debug, PID: 9951
    java.lang.IllegalAccessError: Method 'void de.idnow.core.network.e.$invoke$special$k()' is inaccessible to class 'de.idnow.core.network.e$$ExternalSyntheticLambda0' (declaration of 'de.idnow.core.network.e$$ExternalSyntheticLambda0' appears in /data/app/~~It_zsZu7MqOMJ_U4P_XrHA==/eu.qonto.qonto.debug-owNcK6gvAYWZ3eBANuYgZg==/base.apk!classes32.dex)
        at de.idnow.core.network.e$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8512)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by sebastian-schipor-idnow** [comment]
Are you applying any proguard rules when building your app?

**Comment by bastienpaulfr** [comment]
I'm building debug flavor, so I do not think so, but I'll double check

**Comment by bastienpaulfr** [comment]
Without changing anything, I've succeed in proceeding into video selfie... (in restarting from the first AutoIdent screen)

**Comment by sebastian-schipor-idnow** [comment]
Seems to be related to https://github.com/idnow/de.idnow.android.sdk/issues/75 
Let's keep an eye on these when they reproduce again.

**Comment by sebastian-schipor-idnow** [comment]
@bastienpaulfr we released a new AI SDK v5.0.0. Please try it out and let us know if the issue still persists.
