### ISSUE TITLE
java.lang.ClassNotFoundException: com.readid.core.configuration.MRZConfiguration error

### ISSUE THREAD

**Issue by serhat-oz** [idnow/de.idnow.android.sdk#86]
We are getting the following error upon clicking on start now in nfc flow. 

![image](https://user-images.githubusercontent.com/36677905/203760543-ff9a1f45-0e3a-4452-8e99-963cc3bde933.png)

System.err               W  java.lang.ClassNotFoundException: com.readid.core.configuration.MRZConfiguration
System.err               W     at java.lang.Class.classForName(Native Method)
System.err               W     at java.lang.Class.forName(Class.java:453)
System.err               W     at java.lang.Class.forName(Class.java:378)
System.err               W     at de.idnow.core.ui.IDnowActivity.C(SourceFile:2165)
System.err               W     at de.idnow.core.ui.IDnowActivity.b(SourceFile:1682)
System.err               W     at de.idnow.core.ui.main.u.onClick(SourceFile:248)
System.err               W     at android.view.View.performClick(View.java:7352)
System.err               W     at android.widget.TextView.performClick(TextView.java:14177)
System.err               W     at android.view.View.performClickInternal(View.java:7318)
System.err               W     at android.view.View.access$3200(View.java:846)
System.err               W     at android.view.View$PerformClick.run(View.java:27800)
System.err               W     at android.os.Handler.handleCallback(Handler.java:873)
System.err               W     at android.os.Handler.dispatchMessage(Handler.java:99)
System.err               W     at android.os.Looper.loop(Looper.java:214)
System.err               W     at android.app.ActivityThread.main(ActivityThread.java:7037)
System.err               W     at java.lang.reflect.Method.invoke(Native Method)
System.err               W     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
System.err               W     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
System.err               W  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.readid.core.configuration.MRZConfiguration" on path: DexPathList[[zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.veripark.ykbnl.dev-uR0s3TXRuFm-sxD29La9gA==/base.apk"],nativeLibraryDirectories=[/data/app/com.veripark.ykbnl.dev-uR0s3TXRuFm-sxD29La9gA==/lib/arm64, /data/app/com.veripark.ykbnl.dev-uR0s3TXRuFm-sxD29La9gA==/base.apk!/lib/arm64-v8a, /system/lib64]]
System.err               W     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
System.err               W     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
System.err               W     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

Updated gradle file is below.
![image](https://user-images.githubusercontent.com/36677905/203760775-bf60c15f-ffb9-420d-9a09-1fe3b4741dba.png)
![image](https://user-images.githubusercontent.com/36677905/203760800-a543c2b1-7a0e-4d0d-a218-f892ab5f0c40.png)
![image](https://user-images.githubusercontent.com/36677905/203760830-2ff0a916-7f90-4037-9407-dd4c13c208dc.png)

**Comment by sebastian-schipor-idnow** [comment]
@serhat-oz thanks for reaching out!
It looks like you're missing some dependencies. 
In order to use the NFC reading functionality, you will need some additional AAR files to be placed inside your `libs/ `folder + some additional dependencies in your build.gradle file.

Please reach out to IDnow Customer Support to receive those dependencies.

**Comment by sebastian-schipor-idnow** [comment]
@serhat-oz also, please make sure to add this line in your application's build.gradle file:
   `implementation fileTree(include: ['*.jar', '*.aar'], dir: 'libs')`

**Comment by sebastian-schipor-idnow** [comment]
Hello @serhat-oz 
The errors clearly suggests that you added the dependencies twice.

You need to remove the 4 lines where you explicitly implement the "ReadID-..." dependencies. (those are not even all the required readID libraries - there should be 6 of them). In order to not have to write them individually (and more work when you will need to update them), the easiest way is to implement all the libraries inside the `libs` folder.

You just need to have:
`implementation fileTree(include: ['*.jar', '*.aar'], dir: 'libs')`

and the lines between 
```
//ReadID dependencies 
...
//end ReadID dependencies
```

**Comment by sebastianmarschall** [comment]
how can i disable the NFC feature?

**Comment by sebastian-schipor-idnow** [comment]
@sebastianmarschall in oder to disable the NFC Chip reading step during an identification, you need to reach our to CustomerSuccess team and request that they update your customer configuration to not contain the NFC step.

**Comment by sebastianmarschall** [comment]
Thanks for the quick response!
And where do I get the ReadID dependencies from in case I want to use NFC?

**Comment by sebastian-schipor-idnow** [comment]
@sebastianmarschall also from Customer Success team. They will provide you a link from where you can download an archive + instructions to include ReadID based on what version of AI SDK you are using.

**Comment by sebastian-schipor-idnow** [comment]
unfortunately I am only dealing with AI product. I can ping internally someone to take a look at VI repo.
