### ISSUE TITLE
version 5.2.0 Video Selfie Step Out Of Memory Error

### ISSUE THREAD

**Issue by cantez-ceb** [idnow/de.idnow.android.sdk#95]
Hello,

We are trying to upgrade from 5.0.0 to 5.2.0, but we get a fatal exception like below after it is trying to continue video selfie step.

Do you have any suggestion?

`java.lang.OutOfMemoryError: Failed to allocate a 965922856 byte allocation with 25165824 free bytes and 464MB until OOM, target footprint 75413680, growth limit 536870912
                                                                                                    	at com.facetec.sdk.bk.onCreate(Unknown Source:705)
                                                                                                    	at android.app.Fragment.performCreate(Fragment.java:2486)
                                                                                                    	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1261)
                                                                                                    	at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
                                                                                                    	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
                                                                                                    	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
                                                                                                    	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
                                                                                                    	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3057)
                                                                                                    	at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3004)
                                                                                                    	at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:185)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8586)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8557)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4147)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4312)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2571)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8741)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)`

**Comment by sebastian-schipor-idnow** [comment]
@cantez-ceb we will perform another update of the liveness library, which hopefully will solve this issue. We will let you know as soon as we will release a new version with this change.

**Comment by yusufk-ceb** [comment]
Dear all, 

Our apps also use "Onespan Shielding SDK" as well. When we shield our app, we got above error otherwise autoident seems working. We asked above question to "onespan" as well. So their response is below;

Do you have any idea or is there anyway to disabled this "code integrity checking" ? 

thanks in advance.


**>> We have learned that "Code integrity checking" has been added to the newer version of Facetec SDK. That integrity check is unable to pass when the application is shielded. But, it is throwing an exception in your case 
-java.lang.OutOfMemoryError: Failed to allocate a 965922856 byte allocation with 25165824 free bytes and 464MB until OOM, target footprint 75413680, growth limit 536870912  -> at com.facetec.sdk.bk.onCreate(Unknown Source:705)". 

Unfortunately, there is nothing we can do at our end (The mechanism of shielding the application can not exclude class and shield has to inject security code in the classes to be able to protect the complete application) . But, currently there are a limited available options:

- Try to ask the service provider to disable to integrity check and depend on shield for the security. 
- Integrate the older version which is compatible with shield.**
